<?php

namespace Database\Seeders;

use App\Models\Pet;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AdoptionPetsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pets = [
            [
                'pet_name' => 'Xioming',
                'species' => 'Cat',
                'breed' => 'Norwegian Forest cat',
                'birthdate' => Carbon::now()->subYears(5),
                'gender' => 'Female',
                'notes' => 'A medium-furred white she-cat with heterochromatic golden and green eyes; with average curled ears',
                'pet_weight' => 8.9,
                'pet_image' => 'images/adoption pets/xioming.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Cozmo',
                'species' => 'Cat',
                'breed' => 'American Curl',
                'birthdate' => Carbon::now()->subYears(6),
                'gender' => 'Male',
                'notes' => 'A medium-furred white cat with dichroic golden and green eyes; and is deaf, with large curled ears',
                'pet_weight' => 7.7,
                'pet_image' => 'images/adoption pets/cozmo.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Chase',
                'species' => 'Cat',
                'breed' => 'Cornish Rex',
                'birthdate' => Carbon::now()->subYears(8),
                'gender' => 'Female',
                'notes' => 'Loving, A long-furred silver red tom with blue eyes',
                'pet_weight' => 6.9,
                'pet_image' => 'images/adoption pets/chase.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Buster',
                'species' => 'Dog',
                'breed' => 'Bulldog',
                'birthdate' => Carbon::now()->subYears(4),
                'gender' => 'Male',
                'notes' => 'A stocky brindle dog with a massive underbite and a heart of gold',
                'pet_weight' => 23,
                'pet_image' => 'images/adoption pets/buster.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Bella',
                'species' => 'Cat',
                'breed' => 'Scottish Fold',
                'birthdate' => Carbon::now()->subYears(2),
                'gender' => 'Female',
                'notes' => 'A small grey tabby with tightly folded ears and a very expressive tail',
                'pet_weight' => 4,
                'pet_image' => 'images/adoption pets/bella.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Shadow',
                'species' => 'Dog',
                'breed' => 'German Shepherd',
                'birthdate' => Carbon::now()->subYears(6),
                'gender' => 'Male',
                'notes' => 'A large black and tan dog with alert ears and a highly focused gaze',
                'pet_weight' => 38,
                'pet_image' => 'images/adoption pets/shadow.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Oliver',
                'species' => 'Cat',
                'breed' => 'British Shorthair',
                'birthdate' => Carbon::now()->subYears(3),
                'gender' => 'Male',
                'notes' => 'A chubby blue-grey tomcat with round copper eyes and a plush coat',
                'pet_weight' => 6,
                'pet_image' => 'images/adoption pets/oliver.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Daisy',
                'species' => 'Dog',
                'breed' => 'Golden Retriever',
                'birthdate' => Carbon::now()->subYears(1),
                'gender' => 'Female',
                'notes' => 'A fluffy cream-colored puppy with floppy ears and a constantly wagging tail',
                'pet_weight' => 25,
                'pet_image' => 'images/adoption pets/daisy.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Smokey',
                'species' => 'Cat',
                'breed' => 'Russian Blue',
                'birthdate' => Carbon::now()->subYears(4),
                'gender' => 'Male',
                'notes' => 'A sleek short-haired cat with a silvery-green sheen and striking emerald eyes',
                'pet_weight' => 5,
                'pet_image' => 'images/adoption pets/smokey.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Lottie',
                'species' => 'Cat',
                'breed' => 'Puspin',
                'birthdate' => Carbon::now()->subYears(3),
                'gender' => 'Female',
                'notes' => 'A red and white low-riding cat with big fox-like ears and long tail',
                'pet_weight' => 11,
                'pet_image' => 'images/adoption pets/lottie.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'pet_name' => 'Naya',
                'species' => 'Cat',
                'breed' => 'Puspin',
                'birthdate' => Carbon::now()->subYears(4),
                'gender' => 'Female',
                'notes' => 'A shy white and yellow fierce cat with green eyes',
                'pet_weight' => 4.5,
                'pet_image' => 'images/adoption pets/naya.jpg',
                'source_module' => 'adoption_pets',
                'source_module_id' => null,
                'is_approved' => true,
                'pet_status' => 'available',
                'is_neutered' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($pets as $pet) {
            $createdPet = Pet::create($pet);
            // Update source_module_id to point to self
            $createdPet->update(['source_module_id' => $createdPet->pet_id]);
        }
    }
}
