<?php

namespace Database\Seeders;

use App\Models\MissingPet;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MissingPetsSeeder extends Seeder
{
    public function run(): void
    {
        $barangays = [
            'Burol I', 'Burol II', 'Burol III', 'Burol Main', 'Datu Esmael (Bago-A-Ingud)',
            'Emmanuel Bergaod I', 'Emmanuel Bergaod II', 'Fatima I', 'Fatima II', 'Fatima III',
            'H-2 (Sta. Veronica)', 'Langkaan I (Humayao)', 'Langkaan II', 'Luzviminda I', 'Luzviminda II',
            'Paliparan I', 'Paliparan II', 'Paliparan III', 'Sabang', 'Saint Peter I',
            'Saint Peter II', 'Salawag', 'Salitran I', 'Salitran II', 'Salitran III', 'Salitran IV',
            'Sampaloc I (Pala-Pala)', 'Sampaloc II (Bucal/Malinta)', 'Sampaloc III (Piela)',
            'Sampaloc IV (Talisayan/Bautista)', 'Sampaloc V (New Era)', 'San Augustin I',
            'San Augustin II (R. Tirona)', 'San Augustin III', 'San Andres I', 'San Andres II',
            'San Antonio De Padua I', 'San Antonio De Padua II', 'San Dionisio', 'San Esteban',
            'San Fransisco I', 'San Fransisco II', 'San Isidro Labrador I', 'San Isidro Labrador II',
            'San Jose', 'San Juan', 'San Lorenzo Ruiz I', 'San Lorenzo Ruiz II', 'San Luis I',
            'San Luis II', 'San Manuel I', 'San Manuel II', 'San Mateo', 'San Miguel I',
            'San Miguel II', 'San Nicolas I', 'San Nicolas II', 'San Roque', 'San Simon',
            'Santa Cristina I', 'Santa Cristina II', 'Santa Cruz I', 'Santa Cruz II', 'Santa Fe',
            'Santa Lucia', 'Santa Maria', 'Santo Cristo', 'Santo Niño I', 'Santo Niño II',
            'Victoria Reyes', 'Zone I', 'Zone I-A', 'Zone II', 'Zone III', 'Zone IV'
        ];

        $pets = [
            [
                'name' => 'Max',
                'species' => 'Dog',
                'breed' => 'Golden Retriever',
                'age' => 3,
                'weight' => 28.5,
                'color' => 'Golden',
                'gender' => 'male',
                'last_seen_at' => Carbon::now()->subDays(2),
                'description' => 'Friendly and playful golden retriever with a white chest mark. Was last seen near the park.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing pets/max.jpg',
            ],
            [
                'name' => 'Luna',
                'species' => 'Cat',
                'breed' => 'Siamese',
                'age' => 2,
                'weight' => 4.2,
                'color' => 'Cream and brown',
                'gender' => 'female',
                'last_seen_at' => Carbon::now()->subDays(5),
                'description' => 'Blue-eyed Siamese cat with distinctive color points. Very vocal and friendly.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/luna.jpg',
            ],
            [
                'name' => 'Bruno',
                'species' => 'Dog',
                'breed' => 'German Shepherd',
                'age' => 5,
                'weight' => 35.0,
                'color' => 'Black and tan',
                'gender' => 'male',
                'last_seen_at' => Carbon::now()->subDays(1),
                'description' => 'Large German Shepherd with alert ears. Has a scar on left front leg.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/bruno.jpg',
            ],
            [
                'name' => 'Mochi',
                'species' => 'Cat',
                'breed' => 'British Shorthair',
                'age' => 1,
                'weight' => 3.8,
                'color' => 'Gray',
                'gender' => 'male',
                'last_seen_at' => Carbon::now()->subDays(3),
                'description' => 'Round-faced gray kitten with copper eyes. Very shy around strangers.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/mochi.jpg',
            ],
            [
                'name' => 'Bella',
                'species' => 'Dog',
                'breed' => 'Labrador',
                'age' => 4,
                'weight' => 25.0,
                'color' => 'Chocolate',
                'gender' => 'female',
                'last_seen_at' => Carbon::now()->subDays(7),
                'description' => 'Chocolate Labrador with a red collar. Very friendly and loves children.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/bella.jpg',
            ],
            [
                'name' => 'Simba',
                'species' => 'Cat',
                'breed' => 'Puspin',
                'age' => 2,
                'weight' => 4.5,
                'color' => 'Orange tabby',
                'gender' => 'male',
                'last_seen_at' => Carbon::now()->subDays(4),
                'description' => 'Orange tabby with white paws and chest. Has a pink nose and green eyes.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/simba.jpg',
            ],
            [
                'name' => 'Rocky',
                'species' => 'Dog',
                'breed' => 'Bull Terrier',
                'age' => 6,
                'weight' => 30.0,
                'color' => 'White',
                'gender' => 'male',
                'last_seen_at' => Carbon::now()->subDays(6),
                'description' => 'White Bull Terrier with a brown spot on left ear. Very energetic and playful.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/rocky.jpg',
            ],
            [
                'name' => 'Cleo',
                'species' => 'Cat',
                'breed' => 'Persian',
                'age' => 3,
                'weight' => 5.2,
                'color' => 'White',
                'gender' => 'female',
                'last_seen_at' => Carbon::now()->subDays(2),
                'description' => 'Long-haired white Persian with blue eyes. Has a pink collar with bell.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/cleo.jpg',
            ],
            [
                'name' => 'Duke',
                'species' => 'Dog',
                'breed' => 'Beagle',
                'age' => 2,
                'weight' => 12.0,
                'color' => 'Tri-color',
                'gender' => 'male',
                'last_seen_at' => Carbon::now()->subDays(8),
                'description' => 'Tri-color beagle puppy with floppy ears. Very curious and loves to sniff.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/duke.jpg',
            ],
            [
                'name' => 'Whiskers',
                'species' => 'Cat',
                'breed' => 'Maine Coon',
                'age' => 4,
                'weight' => 7.0,
                'color' => 'Brown tabby',
                'gender' => 'female',
                'last_seen_at' => Carbon::now()->subDays(10),
                'description' => 'Large brown tabby Maine Coon with a bushy tail. Very gentle and loves to cuddle.',
                'location' => $barangays[array_rand($barangays)] . ', Dasmariñas, Cavite',
                'status' => 'missing',
                'photo_img' => 'images/missing-pets/whiskers.jpg',
            ],
        ];

        foreach ($pets as $pet) {
            MissingPet::create($pet);
        }
    }
}